
# SEO settings
title: Jordan Tuwiner
description: "Bitcoin"
url: "https://www.jordantuwiner.com"
baseurl: ""

google_analytics: UA-46723158-1
repo: https://github.com/JTuwiner/jtuwiner.github.io
disqus_shortname:

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: false

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Jordan Tuwiner
  job      : None
  bio      : "I’m passionate about Bitcoin, economics, and freedom. I created Buy Bitcoin Worldwide, where I help people buy bitcoin."
  thumb    : /images/author.jpg
  email    : jordan@jordantuwiner.com
  url      : https://www.jordantuwiner.com/
  github   : http://github.com/JTuwiner
  twitter  : http://twitter.com/jordantuwiner
  facebook : 
  linkedin : 

# social settings
og_locale: "en"
twitter_card: "summary_large_image"
twitter_site: "@jordantuwiner"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
